// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

package serve

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	NodeId               int64    `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_055800a0d35f75c0, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetNodeId() int64 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

type Response struct {
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Base32               string   `protobuf:"bytes,3,opt,name=base32,proto3" json:"base32,omitempty"`
	Base58               string   `protobuf:"bytes,4,opt,name=base58,proto3" json:"base58,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_055800a0d35f75c0, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Response) GetBase32() string {
	if m != nil {
		return m.Base32
	}
	return ""
}

func (m *Response) GetBase58() string {
	if m != nil {
		return m.Base58
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "snowflake.app.serve.Request")
	proto.RegisterType((*Response)(nil), "snowflake.app.serve.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GenerateServiceClient is the client API for GenerateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GenerateServiceClient interface {
	Generator(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type generateServiceClient struct {
	cc *grpc.ClientConn
}

func NewGenerateServiceClient(cc *grpc.ClientConn) GenerateServiceClient {
	return &generateServiceClient{cc}
}

func (c *generateServiceClient) Generator(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/snowflake.app.serve.GenerateService/Generator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GenerateServiceServer is the server API for GenerateService service.
type GenerateServiceServer interface {
	Generator(context.Context, *Request) (*Response, error)
}

func RegisterGenerateServiceServer(s *grpc.Server, srv GenerateServiceServer) {
	s.RegisterService(&_GenerateService_serviceDesc, srv)
}

func _GenerateService_Generator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenerateServiceServer).Generator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/snowflake.app.serve.GenerateService/Generator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenerateServiceServer).Generator(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _GenerateService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "snowflake.app.serve.GenerateService",
	HandlerType: (*GenerateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generator",
			Handler:    _GenerateService_Generator_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "config.proto",
}

func init() { proto.RegisterFile("config.proto", fileDescriptor_config_055800a0d35f75c0) }

var fileDescriptor_config_055800a0d35f75c0 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0x4b,
	0xcb, 0x4c, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x2e, 0xce, 0xcb, 0x2f, 0x4f, 0xcb,
	0x49, 0xcc, 0x4e, 0xd5, 0x4b, 0x2c, 0x28, 0xd0, 0x2b, 0x4e, 0x2d, 0x2a, 0x4b, 0x55, 0x52, 0xe2,
	0x62, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe7, 0x62, 0xcf, 0xcb, 0x4f, 0x49,
	0x8d, 0xcf, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x62, 0x03, 0x71, 0x3d, 0x53, 0x94,
	0xbc, 0xb8, 0x38, 0x82, 0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0xf8, 0xb8, 0x98, 0x32,
	0x53, 0x24, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0x98, 0x32, 0x53, 0x84, 0xc4, 0xb8, 0xd8, 0x92,
	0x12, 0x8b, 0x53, 0x8d, 0x8d, 0x24, 0x98, 0xc1, 0x62, 0x50, 0x1e, 0x4c, 0xdc, 0xd4, 0x42, 0x82,
	0x05, 0x21, 0x6e, 0x6a, 0x61, 0x14, 0xcb, 0xc5, 0xef, 0x9e, 0x9a, 0x97, 0x5a, 0x94, 0x58, 0x92,
	0x1a, 0x9c, 0x5a, 0x54, 0x96, 0x99, 0x9c, 0x2a, 0xe4, 0xc5, 0xc5, 0x09, 0x15, 0xca, 0x2f, 0x12,
	0x92, 0xd1, 0xc3, 0xe2, 0x4a, 0x3d, 0xa8, 0x13, 0xa5, 0x64, 0x71, 0xc8, 0x42, 0x1c, 0xa7, 0xc4,
	0xe0, 0x64, 0xc1, 0x25, 0x9e, 0x9c, 0x9f, 0x8b, 0x4d, 0x55, 0x00, 0x63, 0x14, 0x2b, 0x98, 0xb1,
	0x8a, 0x49, 0x38, 0x18, 0x2e, 0xed, 0x58, 0x50, 0xa0, 0x07, 0x72, 0x47, 0x6a, 0x12, 0x1b, 0x38,
	0x90, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x72, 0xcd, 0xc6, 0x75, 0x34, 0x01, 0x00, 0x00,
}
